baseURL = "https://paulrosoman.com/"
languageCode = "en-us"
title = "Paul Rosoman"
theme = "hugo-initio"
publishDir = "public"

[params]
    name = "Paul Rosoman"
    description = "International Concert Organist"
    email = "paul@paulrosoman.com"
    phone = ""
    address = "P.O. Box 5845<br>Wellington 6145<br>New Zealand"
    year = 2019
    background = ""
    favicon = "images/pr_favicon.ico"
    DateForm = "January 2, 2006"

    showSubheader = true
    showServices = false
    showRecentWorks = false
    showDownload = false
    showClients = false

    footerEnableContact = true
    footerEnableFollowme = true
    footerEnableTextWidget = false
    footerEnableFormWidget = false

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "biography"
    url = "/biography"
    weight = 2
[[menu.main]]
    name = "diary"
    url = "/performance-diary/"
    weight = 3
[[menu.main]]
    name = "press book"
    url = "/reviews"
    weight = 4
[[menu.main]]
    name = "contact"
    url = "/contact"
    weight = 5
[[menu.main]]
    name = "shop"
    url = "/shop"
    weight = 6

[params.google.analytics]
    trackerID = "UA-23993065-2"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/paul.rosoman"
    icon = "fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "linkedin"
	url = "https://nz.linkedin.com/in/paul-rosoman-5528b737"
    icon = "fa-linkedin-square"
    footer = true
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "instagram"
	url = "https://instagram.com/paulrosoman"
    icon = "fa-instagram"
    footer = true
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "email"
	url = "mailto:hello@paulrosoman.com"
    icon = "fa-envelope"
    footer = false
    sharethis = true
    network = "email"

[blackfriday]
    extensions = ["hardLineBreak"]
